name: rust-build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get package name
      run: echo "CARGO_PKG_NAME=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name')"
    - name: Build
      run: cargo build --release
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        files: target/release/${{ env.CARGO_PKG_NAME }}
